# Generated by Django 3.2.9 on 2021-12-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_age', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
