# Generated by Django 3.2.9 on 2021-12-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=600)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
