# Generated by Django 3.2.9 on 2021-12-16 14:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', ckeditor.fields.RichTextField()),
                ('post', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
