# Generated by Django 3.2.9 on 2021-12-22 11:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_blog_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('speciality', ckeditor.fields.RichTextField()),
                ('city', models.CharField(max_length=40)),
            ],
        ),
    ]
