# Generated by Django 3.2.9 on 2021-12-29 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_add_content_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_content_video',
            name='name',
        ),
        migrations.DeleteModel(
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blog_data',
            name='blog_author',
        ),
        migrations.DeleteModel(
            name='doctor_data',
        ),
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='post',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.DeleteModel(
            name='add_content_video',
        ),
        migrations.DeleteModel(
            name='blog_data',
        ),
    ]
