# Generated by Django 3.2.9 on 2021-12-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20211229_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=200)),
                ('package_cate', models.CharField(max_length=200)),
                ('days', models.IntegerField()),
                ('package_image', models.ImageField(upload_to='package_images')),
                ('package_desc', models.CharField(max_length=1000)),
                ('package_price', models.IntegerField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
