# Generated by Django 3.2.9 on 2021-12-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('card_no', models.IntegerField()),
                ('expiry', models.DateField()),
                ('cvv', models.IntegerField()),
            ],
        ),
    ]
